# Generated by Django 5.0.6 on 2024-06-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=100)),
                ('catagory_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Design_Catagory',
            fields=[
                ('design_catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('design_catagory_name', models.CharField(max_length=100)),
                ('design_catagory_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Display_Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_title', models.CharField(max_length=100)),
                ('product_added_date', models.DateTimeField(auto_now_add=True)),
                ('product_catagory', models.ManyToManyField(to='leather_web.catagory')),
                ('product_color', models.ManyToManyField(to='leather_web.color')),
                ('product_design_catagory', models.ManyToManyField(to='leather_web.design_catagory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leather_web.display_product')),
            ],
        ),
    ]
