# Generated by Django 5.0.6 on 2024-06-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0002_home_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leather_web.display_product', unique=True),
        ),
    ]
