# Generated by Django 5.0.6 on 2024-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0004_description_volume_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='volume_description',
        ),
        migrations.AddField(
            model_name='display_product',
            name='volume_description',
            field=models.ManyToManyField(to='leather_web.volume_description'),
        ),
    ]
