# Generated by Django 5.0.6 on 2024-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0005_remove_description_volume_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_product',
            name='product_description',
        ),
        migrations.AddField(
            model_name='display_product',
            name='text_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display_product',
            name='weight_description',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
