# Generated by Django 5.0.6 on 2024-06-25 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0006_remove_display_product_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_product',
            name='volume_description',
        ),
        migrations.AddField(
            model_name='display_product',
            name='volume_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leather_web.volume_description'),
            preserve_default=False,
        ),
    ]
