# Generated by Django 5.0.6 on 2024-06-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0007_remove_display_product_volume_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='catagory_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design_catagory',
            name='design_catagory_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display_product',
            name='product_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leather_web.productimage'),
            preserve_default=False,
        ),
    ]
