# Generated by Django 5.0.6 on 2024-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0008_catagory_catagory_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_product',
            name='product_image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
