# Generated by Django 5.0.6 on 2024-06-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0009_alter_display_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='display_product',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leather_web.productimage'),
        ),
    ]
