# Generated by Django 5.0.6 on 2024-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0010_productimage_alter_display_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='display_product',
            name='product_image',
            field=models.ManyToManyField(to='leather_web.productimage'),
        ),
    ]
