# Generated by Django 5.0.6 on 2024-06-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0011_remove_display_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram_Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.ImageField(upload_to='instagram_images/')),
                ('post_link', models.URLField()),
                ('home_page_available', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='display_product',
            name='Instagram_Post',
            field=models.ManyToManyField(blank=True, null=True, to='leather_web.instagram_post'),
        ),
    ]
