# Generated by Django 5.0.6 on 2024-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0012_instagram_post_display_product_instagram_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
