# Generated by Django 5.0.6 on 2024-06-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0015_user_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_record',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_record',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
