# Generated by Django 5.0.6 on 2024-07-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_web', '0017_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='gift_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leather_web.display_product'),
        ),
    ]
